CREATE TABLE ACCOUNT (
    ACCOUNT_ID INTEGER NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(50),
    ACCOUNT_NUM VARCHAR(50),
    STATUS INTEGER
);


CREATE TABLE TRANSACTION_TYPE (
    TYPE INTEGER  PRIMARY KEY,
    DESCRIPTION VARCHAR(50)
    );

CREATE SEQUENCE  SEQ_ACCOUNT
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
   
CREATE SEQUENCE  SEQ_TRANSACTION
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
   
   
CREATE TABLE TRANSACTION (
    TRANSACTION_ID INTEGER NOT NULL PRIMARY KEY,
    TYPE INTEGER,
    FOREIGN KEY (TYPE) REFERENCES TRANSACTION_TYPE,
    ACCOUNT_ID INTEGER,
    FOREIGN KEY ( ACCOUNT_ID) REFERENCES ACCOUNT,
    AMOUNT NUMBER(9,2),
    TRANSACTION_DATE DATE,
    STATUS INTEGER
    
);

select * from account;
delete from account where ACCOUNT_ID=1;
drop table transaction;
drop table account;


SELECT SEQ_TRANSACTION.NEXTVAL FROM DUAL;




"select * from account where ACCOUNT_NAME ='" + accountName + "'";

